-- MySQL Script generated by MySQL Workbench
-- seg 03 mai 2021 21:27:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema btc_bot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema btc_bot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `btc_bot` ;
USE `btc_bot` ;

-- -----------------------------------------------------
-- Table `btc_bot`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btc_bot`.`price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(18) NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
